// Code generated by protoc-gen-go. DO NOT EDIT.
// source: openfeed_api.proto

package openfeed

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result int32

const (
	Result_UNKNOWN_RESULT          Result = 0
	Result_SUCCESS                 Result = 1
	Result_INVALID_SYMBOL          Result = 116
	Result_INVALID_MARKET_ID       Result = 117
	Result_INVALID_EXCHANGE        Result = 118
	Result_INVALID_CHANNEL_ID      Result = 119
	Result_MALFORMED_MESSAGE       Result = 120
	Result_UNEXPECTED_MESSAGE      Result = 121
	Result_NOT_SUBSCRIBED          Result = 122
	Result_DUPLICATE_SUBSCRIPTION  Result = 123
	Result_INVALID_CREDENTIALS     Result = 124
	Result_INSUFFICIENT_PRIVILEGES Result = 125
	Result_AUTHENTICATION_REQUIRED Result = 126
	Result_GENERIC_FAILURE         Result = 127
)

var Result_name = map[int32]string{
	0:   "UNKNOWN_RESULT",
	1:   "SUCCESS",
	116: "INVALID_SYMBOL",
	117: "INVALID_MARKET_ID",
	118: "INVALID_EXCHANGE",
	119: "INVALID_CHANNEL_ID",
	120: "MALFORMED_MESSAGE",
	121: "UNEXPECTED_MESSAGE",
	122: "NOT_SUBSCRIBED",
	123: "DUPLICATE_SUBSCRIPTION",
	124: "INVALID_CREDENTIALS",
	125: "INSUFFICIENT_PRIVILEGES",
	126: "AUTHENTICATION_REQUIRED",
	127: "GENERIC_FAILURE",
}

var Result_value = map[string]int32{
	"UNKNOWN_RESULT":          0,
	"SUCCESS":                 1,
	"INVALID_SYMBOL":          116,
	"INVALID_MARKET_ID":       117,
	"INVALID_EXCHANGE":        118,
	"INVALID_CHANNEL_ID":      119,
	"MALFORMED_MESSAGE":       120,
	"UNEXPECTED_MESSAGE":      121,
	"NOT_SUBSCRIBED":          122,
	"DUPLICATE_SUBSCRIPTION":  123,
	"INVALID_CREDENTIALS":     124,
	"INSUFFICIENT_PRIVILEGES": 125,
	"AUTHENTICATION_REQUIRED": 126,
	"GENERIC_FAILURE":         127,
}

func (x Result) String() string {
	return proto.EnumName(Result_name, int32(x))
}

func (Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{0}
}

type SubscriptionType int32

const (
	SubscriptionType_ALL               SubscriptionType = 0
	SubscriptionType_QUOTE             SubscriptionType = 1
	SubscriptionType_QUOTE_PARTICIPANT SubscriptionType = 2
	SubscriptionType_DEPTH_PRICE       SubscriptionType = 3
	SubscriptionType_DEPTH_ORDER       SubscriptionType = 4
	SubscriptionType_TRADES            SubscriptionType = 5
	SubscriptionType_CUMLATIVE_VOLUME  SubscriptionType = 6
	SubscriptionType_OHLC              SubscriptionType = 7
	SubscriptionType_OHLC_NON_REGULAR  SubscriptionType = 8
)

var SubscriptionType_name = map[int32]string{
	0: "ALL",
	1: "QUOTE",
	2: "QUOTE_PARTICIPANT",
	3: "DEPTH_PRICE",
	4: "DEPTH_ORDER",
	5: "TRADES",
	6: "CUMLATIVE_VOLUME",
	7: "OHLC",
	8: "OHLC_NON_REGULAR",
}

var SubscriptionType_value = map[string]int32{
	"ALL":               0,
	"QUOTE":             1,
	"QUOTE_PARTICIPANT": 2,
	"DEPTH_PRICE":       3,
	"DEPTH_ORDER":       4,
	"TRADES":            5,
	"CUMLATIVE_VOLUME":  6,
	"OHLC":              7,
	"OHLC_NON_REGULAR":  8,
}

func (x SubscriptionType) String() string {
	return proto.EnumName(SubscriptionType_name, int32(x))
}

func (SubscriptionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{1}
}

/// Openfeed Server request
type OpenfeedGatewayRequest struct {
	// Types that are valid to be assigned to Data:
	//	*OpenfeedGatewayRequest_LoginRequest
	//	*OpenfeedGatewayRequest_LogoutRequest
	//	*OpenfeedGatewayRequest_SubscriptionRequest
	//	*OpenfeedGatewayRequest_InstrumentRequest
	//	*OpenfeedGatewayRequest_InstrumentReferenceRequest
	//	*OpenfeedGatewayRequest_ExchangeRequest
	Data                 isOpenfeedGatewayRequest_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *OpenfeedGatewayRequest) Reset()         { *m = OpenfeedGatewayRequest{} }
func (m *OpenfeedGatewayRequest) String() string { return proto.CompactTextString(m) }
func (*OpenfeedGatewayRequest) ProtoMessage()    {}
func (*OpenfeedGatewayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{0}
}

func (m *OpenfeedGatewayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenfeedGatewayRequest.Unmarshal(m, b)
}
func (m *OpenfeedGatewayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenfeedGatewayRequest.Marshal(b, m, deterministic)
}
func (m *OpenfeedGatewayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenfeedGatewayRequest.Merge(m, src)
}
func (m *OpenfeedGatewayRequest) XXX_Size() int {
	return xxx_messageInfo_OpenfeedGatewayRequest.Size(m)
}
func (m *OpenfeedGatewayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenfeedGatewayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenfeedGatewayRequest proto.InternalMessageInfo

type isOpenfeedGatewayRequest_Data interface {
	isOpenfeedGatewayRequest_Data()
}

type OpenfeedGatewayRequest_LoginRequest struct {
	LoginRequest *LoginRequest `protobuf:"bytes,1,opt,name=loginRequest,proto3,oneof"`
}

type OpenfeedGatewayRequest_LogoutRequest struct {
	LogoutRequest *LogoutRequest `protobuf:"bytes,2,opt,name=logoutRequest,proto3,oneof"`
}

type OpenfeedGatewayRequest_SubscriptionRequest struct {
	SubscriptionRequest *SubscriptionRequest `protobuf:"bytes,3,opt,name=subscriptionRequest,proto3,oneof"`
}

type OpenfeedGatewayRequest_InstrumentRequest struct {
	InstrumentRequest *InstrumentRequest `protobuf:"bytes,4,opt,name=instrumentRequest,proto3,oneof"`
}

type OpenfeedGatewayRequest_InstrumentReferenceRequest struct {
	InstrumentReferenceRequest *InstrumentReferenceRequest `protobuf:"bytes,5,opt,name=instrumentReferenceRequest,proto3,oneof"`
}

type OpenfeedGatewayRequest_ExchangeRequest struct {
	ExchangeRequest *ExchangeRequest `protobuf:"bytes,6,opt,name=exchangeRequest,proto3,oneof"`
}

func (*OpenfeedGatewayRequest_LoginRequest) isOpenfeedGatewayRequest_Data() {}

func (*OpenfeedGatewayRequest_LogoutRequest) isOpenfeedGatewayRequest_Data() {}

func (*OpenfeedGatewayRequest_SubscriptionRequest) isOpenfeedGatewayRequest_Data() {}

func (*OpenfeedGatewayRequest_InstrumentRequest) isOpenfeedGatewayRequest_Data() {}

func (*OpenfeedGatewayRequest_InstrumentReferenceRequest) isOpenfeedGatewayRequest_Data() {}

func (*OpenfeedGatewayRequest_ExchangeRequest) isOpenfeedGatewayRequest_Data() {}

func (m *OpenfeedGatewayRequest) GetData() isOpenfeedGatewayRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *OpenfeedGatewayRequest) GetLoginRequest() *LoginRequest {
	if x, ok := m.GetData().(*OpenfeedGatewayRequest_LoginRequest); ok {
		return x.LoginRequest
	}
	return nil
}

func (m *OpenfeedGatewayRequest) GetLogoutRequest() *LogoutRequest {
	if x, ok := m.GetData().(*OpenfeedGatewayRequest_LogoutRequest); ok {
		return x.LogoutRequest
	}
	return nil
}

func (m *OpenfeedGatewayRequest) GetSubscriptionRequest() *SubscriptionRequest {
	if x, ok := m.GetData().(*OpenfeedGatewayRequest_SubscriptionRequest); ok {
		return x.SubscriptionRequest
	}
	return nil
}

func (m *OpenfeedGatewayRequest) GetInstrumentRequest() *InstrumentRequest {
	if x, ok := m.GetData().(*OpenfeedGatewayRequest_InstrumentRequest); ok {
		return x.InstrumentRequest
	}
	return nil
}

func (m *OpenfeedGatewayRequest) GetInstrumentReferenceRequest() *InstrumentReferenceRequest {
	if x, ok := m.GetData().(*OpenfeedGatewayRequest_InstrumentReferenceRequest); ok {
		return x.InstrumentReferenceRequest
	}
	return nil
}

func (m *OpenfeedGatewayRequest) GetExchangeRequest() *ExchangeRequest {
	if x, ok := m.GetData().(*OpenfeedGatewayRequest_ExchangeRequest); ok {
		return x.ExchangeRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OpenfeedGatewayRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OpenfeedGatewayRequest_LoginRequest)(nil),
		(*OpenfeedGatewayRequest_LogoutRequest)(nil),
		(*OpenfeedGatewayRequest_SubscriptionRequest)(nil),
		(*OpenfeedGatewayRequest_InstrumentRequest)(nil),
		(*OpenfeedGatewayRequest_InstrumentReferenceRequest)(nil),
		(*OpenfeedGatewayRequest_ExchangeRequest)(nil),
	}
}

/// Openfeed Server Response
type OpenfeedGatewayMessage struct {
	// Types that are valid to be assigned to Data:
	//	*OpenfeedGatewayMessage_LoginResponse
	//	*OpenfeedGatewayMessage_LogoutResponse
	//	*OpenfeedGatewayMessage_InstrumentResponse
	//	*OpenfeedGatewayMessage_InstrumentReferenceResponse
	//	*OpenfeedGatewayMessage_SubscriptionResponse
	//	*OpenfeedGatewayMessage_MarketStatus
	//	*OpenfeedGatewayMessage_HeartBeat
	//	*OpenfeedGatewayMessage_InstrumentDefinition
	//	*OpenfeedGatewayMessage_MarketSnapshot
	//	*OpenfeedGatewayMessage_MarketUpdate
	//	*OpenfeedGatewayMessage_VolumeAtPrice
	//	*OpenfeedGatewayMessage_Ohlc
	//	*OpenfeedGatewayMessage_ExchangeResponse
	//	*OpenfeedGatewayMessage_InstrumentAction
	Data                 isOpenfeedGatewayMessage_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *OpenfeedGatewayMessage) Reset()         { *m = OpenfeedGatewayMessage{} }
func (m *OpenfeedGatewayMessage) String() string { return proto.CompactTextString(m) }
func (*OpenfeedGatewayMessage) ProtoMessage()    {}
func (*OpenfeedGatewayMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{1}
}

func (m *OpenfeedGatewayMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenfeedGatewayMessage.Unmarshal(m, b)
}
func (m *OpenfeedGatewayMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenfeedGatewayMessage.Marshal(b, m, deterministic)
}
func (m *OpenfeedGatewayMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenfeedGatewayMessage.Merge(m, src)
}
func (m *OpenfeedGatewayMessage) XXX_Size() int {
	return xxx_messageInfo_OpenfeedGatewayMessage.Size(m)
}
func (m *OpenfeedGatewayMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenfeedGatewayMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OpenfeedGatewayMessage proto.InternalMessageInfo

type isOpenfeedGatewayMessage_Data interface {
	isOpenfeedGatewayMessage_Data()
}

type OpenfeedGatewayMessage_LoginResponse struct {
	LoginResponse *LoginResponse `protobuf:"bytes,1,opt,name=loginResponse,proto3,oneof"`
}

type OpenfeedGatewayMessage_LogoutResponse struct {
	LogoutResponse *LogoutResponse `protobuf:"bytes,2,opt,name=logoutResponse,proto3,oneof"`
}

type OpenfeedGatewayMessage_InstrumentResponse struct {
	InstrumentResponse *InstrumentResponse `protobuf:"bytes,3,opt,name=instrumentResponse,proto3,oneof"`
}

type OpenfeedGatewayMessage_InstrumentReferenceResponse struct {
	InstrumentReferenceResponse *InstrumentReferenceResponse `protobuf:"bytes,4,opt,name=instrumentReferenceResponse,proto3,oneof"`
}

type OpenfeedGatewayMessage_SubscriptionResponse struct {
	SubscriptionResponse *SubscriptionResponse `protobuf:"bytes,5,opt,name=subscriptionResponse,proto3,oneof"`
}

type OpenfeedGatewayMessage_MarketStatus struct {
	MarketStatus *MarketStatus `protobuf:"bytes,6,opt,name=marketStatus,proto3,oneof"`
}

type OpenfeedGatewayMessage_HeartBeat struct {
	HeartBeat *HeartBeat `protobuf:"bytes,7,opt,name=heartBeat,proto3,oneof"`
}

type OpenfeedGatewayMessage_InstrumentDefinition struct {
	InstrumentDefinition *InstrumentDefinition `protobuf:"bytes,8,opt,name=instrumentDefinition,proto3,oneof"`
}

type OpenfeedGatewayMessage_MarketSnapshot struct {
	MarketSnapshot *MarketSnapshot `protobuf:"bytes,9,opt,name=marketSnapshot,proto3,oneof"`
}

type OpenfeedGatewayMessage_MarketUpdate struct {
	MarketUpdate *MarketUpdate `protobuf:"bytes,10,opt,name=marketUpdate,proto3,oneof"`
}

type OpenfeedGatewayMessage_VolumeAtPrice struct {
	VolumeAtPrice *VolumeAtPrice `protobuf:"bytes,11,opt,name=volumeAtPrice,proto3,oneof"`
}

type OpenfeedGatewayMessage_Ohlc struct {
	Ohlc *Ohlc `protobuf:"bytes,12,opt,name=ohlc,proto3,oneof"`
}

type OpenfeedGatewayMessage_ExchangeResponse struct {
	ExchangeResponse *ExchangeResponse `protobuf:"bytes,13,opt,name=exchangeResponse,proto3,oneof"`
}

type OpenfeedGatewayMessage_InstrumentAction struct {
	InstrumentAction *InstrumentAction `protobuf:"bytes,14,opt,name=instrumentAction,proto3,oneof"`
}

func (*OpenfeedGatewayMessage_LoginResponse) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_LogoutResponse) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_InstrumentResponse) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_InstrumentReferenceResponse) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_SubscriptionResponse) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_MarketStatus) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_HeartBeat) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_InstrumentDefinition) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_MarketSnapshot) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_MarketUpdate) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_VolumeAtPrice) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_Ohlc) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_ExchangeResponse) isOpenfeedGatewayMessage_Data() {}

func (*OpenfeedGatewayMessage_InstrumentAction) isOpenfeedGatewayMessage_Data() {}

func (m *OpenfeedGatewayMessage) GetData() isOpenfeedGatewayMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetLoginResponse() *LoginResponse {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_LoginResponse); ok {
		return x.LoginResponse
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetLogoutResponse() *LogoutResponse {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_LogoutResponse); ok {
		return x.LogoutResponse
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetInstrumentResponse() *InstrumentResponse {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_InstrumentResponse); ok {
		return x.InstrumentResponse
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetInstrumentReferenceResponse() *InstrumentReferenceResponse {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_InstrumentReferenceResponse); ok {
		return x.InstrumentReferenceResponse
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetSubscriptionResponse() *SubscriptionResponse {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_SubscriptionResponse); ok {
		return x.SubscriptionResponse
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetMarketStatus() *MarketStatus {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_MarketStatus); ok {
		return x.MarketStatus
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetHeartBeat() *HeartBeat {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_HeartBeat); ok {
		return x.HeartBeat
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetInstrumentDefinition() *InstrumentDefinition {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_InstrumentDefinition); ok {
		return x.InstrumentDefinition
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetMarketSnapshot() *MarketSnapshot {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_MarketSnapshot); ok {
		return x.MarketSnapshot
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetMarketUpdate() *MarketUpdate {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_MarketUpdate); ok {
		return x.MarketUpdate
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetVolumeAtPrice() *VolumeAtPrice {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_VolumeAtPrice); ok {
		return x.VolumeAtPrice
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetOhlc() *Ohlc {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_Ohlc); ok {
		return x.Ohlc
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetExchangeResponse() *ExchangeResponse {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_ExchangeResponse); ok {
		return x.ExchangeResponse
	}
	return nil
}

func (m *OpenfeedGatewayMessage) GetInstrumentAction() *InstrumentAction {
	if x, ok := m.GetData().(*OpenfeedGatewayMessage_InstrumentAction); ok {
		return x.InstrumentAction
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OpenfeedGatewayMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OpenfeedGatewayMessage_LoginResponse)(nil),
		(*OpenfeedGatewayMessage_LogoutResponse)(nil),
		(*OpenfeedGatewayMessage_InstrumentResponse)(nil),
		(*OpenfeedGatewayMessage_InstrumentReferenceResponse)(nil),
		(*OpenfeedGatewayMessage_SubscriptionResponse)(nil),
		(*OpenfeedGatewayMessage_MarketStatus)(nil),
		(*OpenfeedGatewayMessage_HeartBeat)(nil),
		(*OpenfeedGatewayMessage_InstrumentDefinition)(nil),
		(*OpenfeedGatewayMessage_MarketSnapshot)(nil),
		(*OpenfeedGatewayMessage_MarketUpdate)(nil),
		(*OpenfeedGatewayMessage_VolumeAtPrice)(nil),
		(*OpenfeedGatewayMessage_Ohlc)(nil),
		(*OpenfeedGatewayMessage_ExchangeResponse)(nil),
		(*OpenfeedGatewayMessage_InstrumentAction)(nil),
	}
}

////////////////////
// Serivce Messages
///////////////////
type Status struct {
	Result               Result   `protobuf:"varint,1,opt,name=result,proto3,enum=org.openfeed.Result" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Service              Service  `protobuf:"varint,3,opt,name=service,proto3,enum=org.openfeed.Service" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{2}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetResult() Result {
	if m != nil {
		return m.Result
	}
	return Result_UNKNOWN_RESULT
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetService() Service {
	if m != nil {
		return m.Service
	}
	return Service_UNKNOWN_SERVICE
}

/// Login
type LoginRequest struct {
	CorrelationId        int64    `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	CorrelationId        int64    `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *LoginResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

/// Logout
type LogoutRequest struct {
	CorrelationId        int64    `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{5}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
	CorrelationId        int64    `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{6}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *LogoutResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

/// Instrument Definition(s), will stream InstrumentDefinition(s)
type InstrumentRequest struct {
	CorrelationId int64  `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*InstrumentRequest_Symbol
	//	*InstrumentRequest_MarketId
	//	*InstrumentRequest_Exchange
	//	*InstrumentRequest_ChannelId
	Request              isInstrumentRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *InstrumentRequest) Reset()         { *m = InstrumentRequest{} }
func (m *InstrumentRequest) String() string { return proto.CompactTextString(m) }
func (*InstrumentRequest) ProtoMessage()    {}
func (*InstrumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{7}
}

func (m *InstrumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstrumentRequest.Unmarshal(m, b)
}
func (m *InstrumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstrumentRequest.Marshal(b, m, deterministic)
}
func (m *InstrumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstrumentRequest.Merge(m, src)
}
func (m *InstrumentRequest) XXX_Size() int {
	return xxx_messageInfo_InstrumentRequest.Size(m)
}
func (m *InstrumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstrumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstrumentRequest proto.InternalMessageInfo

func (m *InstrumentRequest) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *InstrumentRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type isInstrumentRequest_Request interface {
	isInstrumentRequest_Request()
}

type InstrumentRequest_Symbol struct {
	Symbol string `protobuf:"bytes,10,opt,name=symbol,proto3,oneof"`
}

type InstrumentRequest_MarketId struct {
	MarketId int64 `protobuf:"zigzag64,11,opt,name=marketId,proto3,oneof"`
}

type InstrumentRequest_Exchange struct {
	Exchange string `protobuf:"bytes,12,opt,name=exchange,proto3,oneof"`
}

type InstrumentRequest_ChannelId struct {
	ChannelId int32 `protobuf:"zigzag32,13,opt,name=channelId,proto3,oneof"`
}

func (*InstrumentRequest_Symbol) isInstrumentRequest_Request() {}

func (*InstrumentRequest_MarketId) isInstrumentRequest_Request() {}

func (*InstrumentRequest_Exchange) isInstrumentRequest_Request() {}

func (*InstrumentRequest_ChannelId) isInstrumentRequest_Request() {}

func (m *InstrumentRequest) GetRequest() isInstrumentRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *InstrumentRequest) GetSymbol() string {
	if x, ok := m.GetRequest().(*InstrumentRequest_Symbol); ok {
		return x.Symbol
	}
	return ""
}

func (m *InstrumentRequest) GetMarketId() int64 {
	if x, ok := m.GetRequest().(*InstrumentRequest_MarketId); ok {
		return x.MarketId
	}
	return 0
}

func (m *InstrumentRequest) GetExchange() string {
	if x, ok := m.GetRequest().(*InstrumentRequest_Exchange); ok {
		return x.Exchange
	}
	return ""
}

func (m *InstrumentRequest) GetChannelId() int32 {
	if x, ok := m.GetRequest().(*InstrumentRequest_ChannelId); ok {
		return x.ChannelId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*InstrumentRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*InstrumentRequest_Symbol)(nil),
		(*InstrumentRequest_MarketId)(nil),
		(*InstrumentRequest_Exchange)(nil),
		(*InstrumentRequest_ChannelId)(nil),
	}
}

type InstrumentResponse struct {
	CorrelationId        int64    `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	NumberOfDefinitions  int32    `protobuf:"zigzag32,3,opt,name=numberOfDefinitions,proto3" json:"numberOfDefinitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstrumentResponse) Reset()         { *m = InstrumentResponse{} }
func (m *InstrumentResponse) String() string { return proto.CompactTextString(m) }
func (*InstrumentResponse) ProtoMessage()    {}
func (*InstrumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{8}
}

func (m *InstrumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstrumentResponse.Unmarshal(m, b)
}
func (m *InstrumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstrumentResponse.Marshal(b, m, deterministic)
}
func (m *InstrumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstrumentResponse.Merge(m, src)
}
func (m *InstrumentResponse) XXX_Size() int {
	return xxx_messageInfo_InstrumentResponse.Size(m)
}
func (m *InstrumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstrumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstrumentResponse proto.InternalMessageInfo

func (m *InstrumentResponse) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *InstrumentResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InstrumentResponse) GetNumberOfDefinitions() int32 {
	if m != nil {
		return m.NumberOfDefinitions
	}
	return 0
}

/// Instrument References, returns InstrumentReferenceResponse(s)
type InstrumentReferenceRequest struct {
	CorrelationId int64  `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are valid to be assigned to Request:
	//	*InstrumentReferenceRequest_Symbol
	//	*InstrumentReferenceRequest_MarketId
	//	*InstrumentReferenceRequest_Exchange
	//	*InstrumentReferenceRequest_ChannelId
	Request              isInstrumentReferenceRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *InstrumentReferenceRequest) Reset()         { *m = InstrumentReferenceRequest{} }
func (m *InstrumentReferenceRequest) String() string { return proto.CompactTextString(m) }
func (*InstrumentReferenceRequest) ProtoMessage()    {}
func (*InstrumentReferenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{9}
}

func (m *InstrumentReferenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstrumentReferenceRequest.Unmarshal(m, b)
}
func (m *InstrumentReferenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstrumentReferenceRequest.Marshal(b, m, deterministic)
}
func (m *InstrumentReferenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstrumentReferenceRequest.Merge(m, src)
}
func (m *InstrumentReferenceRequest) XXX_Size() int {
	return xxx_messageInfo_InstrumentReferenceRequest.Size(m)
}
func (m *InstrumentReferenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstrumentReferenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstrumentReferenceRequest proto.InternalMessageInfo

func (m *InstrumentReferenceRequest) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *InstrumentReferenceRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type isInstrumentReferenceRequest_Request interface {
	isInstrumentReferenceRequest_Request()
}

type InstrumentReferenceRequest_Symbol struct {
	Symbol string `protobuf:"bytes,10,opt,name=symbol,proto3,oneof"`
}

type InstrumentReferenceRequest_MarketId struct {
	MarketId int64 `protobuf:"zigzag64,11,opt,name=marketId,proto3,oneof"`
}

type InstrumentReferenceRequest_Exchange struct {
	Exchange string `protobuf:"bytes,12,opt,name=exchange,proto3,oneof"`
}

type InstrumentReferenceRequest_ChannelId struct {
	ChannelId int32 `protobuf:"zigzag32,13,opt,name=channelId,proto3,oneof"`
}

func (*InstrumentReferenceRequest_Symbol) isInstrumentReferenceRequest_Request() {}

func (*InstrumentReferenceRequest_MarketId) isInstrumentReferenceRequest_Request() {}

func (*InstrumentReferenceRequest_Exchange) isInstrumentReferenceRequest_Request() {}

func (*InstrumentReferenceRequest_ChannelId) isInstrumentReferenceRequest_Request() {}

func (m *InstrumentReferenceRequest) GetRequest() isInstrumentReferenceRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *InstrumentReferenceRequest) GetSymbol() string {
	if x, ok := m.GetRequest().(*InstrumentReferenceRequest_Symbol); ok {
		return x.Symbol
	}
	return ""
}

func (m *InstrumentReferenceRequest) GetMarketId() int64 {
	if x, ok := m.GetRequest().(*InstrumentReferenceRequest_MarketId); ok {
		return x.MarketId
	}
	return 0
}

func (m *InstrumentReferenceRequest) GetExchange() string {
	if x, ok := m.GetRequest().(*InstrumentReferenceRequest_Exchange); ok {
		return x.Exchange
	}
	return ""
}

func (m *InstrumentReferenceRequest) GetChannelId() int32 {
	if x, ok := m.GetRequest().(*InstrumentReferenceRequest_ChannelId); ok {
		return x.ChannelId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*InstrumentReferenceRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*InstrumentReferenceRequest_Symbol)(nil),
		(*InstrumentReferenceRequest_MarketId)(nil),
		(*InstrumentReferenceRequest_Exchange)(nil),
		(*InstrumentReferenceRequest_ChannelId)(nil),
	}
}

type InstrumentReferenceResponse struct {
	CorrelationId       int64   `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Status              *Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	NumberOfDefinitions int32   `protobuf:"zigzag32,3,opt,name=numberOfDefinitions,proto3" json:"numberOfDefinitions,omitempty"`
	//
	ChannelId            int32    `protobuf:"zigzag32,4,opt,name=channelId,proto3" json:"channelId,omitempty"`
	MarketId             int64    `protobuf:"zigzag64,5,opt,name=marketId,proto3" json:"marketId,omitempty"`
	Symbol               string   `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange             string   `protobuf:"bytes,7,opt,name=exchange,proto3" json:"exchange,omitempty"`
	DdfSymbol            string   `protobuf:"bytes,8,opt,name=ddfSymbol,proto3" json:"ddfSymbol,omitempty"`
	DdfExchange          string   `protobuf:"bytes,9,opt,name=ddfExchange,proto3" json:"ddfExchange,omitempty"`
	DdfBaseCode          string   `protobuf:"bytes,10,opt,name=ddfBaseCode,proto3" json:"ddfBaseCode,omitempty"`
	ExchangeSymbol       string   `protobuf:"bytes,11,opt,name=exchangeSymbol,proto3" json:"exchangeSymbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstrumentReferenceResponse) Reset()         { *m = InstrumentReferenceResponse{} }
func (m *InstrumentReferenceResponse) String() string { return proto.CompactTextString(m) }
func (*InstrumentReferenceResponse) ProtoMessage()    {}
func (*InstrumentReferenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{10}
}

func (m *InstrumentReferenceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstrumentReferenceResponse.Unmarshal(m, b)
}
func (m *InstrumentReferenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstrumentReferenceResponse.Marshal(b, m, deterministic)
}
func (m *InstrumentReferenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstrumentReferenceResponse.Merge(m, src)
}
func (m *InstrumentReferenceResponse) XXX_Size() int {
	return xxx_messageInfo_InstrumentReferenceResponse.Size(m)
}
func (m *InstrumentReferenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstrumentReferenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstrumentReferenceResponse proto.InternalMessageInfo

func (m *InstrumentReferenceResponse) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *InstrumentReferenceResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InstrumentReferenceResponse) GetNumberOfDefinitions() int32 {
	if m != nil {
		return m.NumberOfDefinitions
	}
	return 0
}

func (m *InstrumentReferenceResponse) GetChannelId() int32 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

func (m *InstrumentReferenceResponse) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *InstrumentReferenceResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *InstrumentReferenceResponse) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *InstrumentReferenceResponse) GetDdfSymbol() string {
	if m != nil {
		return m.DdfSymbol
	}
	return ""
}

func (m *InstrumentReferenceResponse) GetDdfExchange() string {
	if m != nil {
		return m.DdfExchange
	}
	return ""
}

func (m *InstrumentReferenceResponse) GetDdfBaseCode() string {
	if m != nil {
		return m.DdfBaseCode
	}
	return ""
}

func (m *InstrumentReferenceResponse) GetExchangeSymbol() string {
	if m != nil {
		return m.ExchangeSymbol
	}
	return ""
}

/// Exchange Request, returns ExchangeResponse.  Gives available exchanges.
type ExchangeRequest struct {
	CorrelationId        int64    `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeRequest) Reset()         { *m = ExchangeRequest{} }
func (m *ExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangeRequest) ProtoMessage()    {}
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{11}
}

func (m *ExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRequest.Unmarshal(m, b)
}
func (m *ExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRequest.Marshal(b, m, deterministic)
}
func (m *ExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRequest.Merge(m, src)
}
func (m *ExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangeRequest.Size(m)
}
func (m *ExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRequest proto.InternalMessageInfo

func (m *ExchangeRequest) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *ExchangeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ExchangeResponse struct {
	CorrelationId        int64                        `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Status               *Status                      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Exchanges            []*ExchangeResponse_Exchange `protobuf:"bytes,3,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ExchangeResponse) Reset()         { *m = ExchangeResponse{} }
func (m *ExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*ExchangeResponse) ProtoMessage()    {}
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{12}
}

func (m *ExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeResponse.Unmarshal(m, b)
}
func (m *ExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeResponse.Marshal(b, m, deterministic)
}
func (m *ExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeResponse.Merge(m, src)
}
func (m *ExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_ExchangeResponse.Size(m)
}
func (m *ExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeResponse proto.InternalMessageInfo

func (m *ExchangeResponse) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *ExchangeResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ExchangeResponse) GetExchanges() []*ExchangeResponse_Exchange {
	if m != nil {
		return m.Exchanges
	}
	return nil
}

type ExchangeResponse_Exchange struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Aliases              []string `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeResponse_Exchange) Reset()         { *m = ExchangeResponse_Exchange{} }
func (m *ExchangeResponse_Exchange) String() string { return proto.CompactTextString(m) }
func (*ExchangeResponse_Exchange) ProtoMessage()    {}
func (*ExchangeResponse_Exchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{12, 0}
}

func (m *ExchangeResponse_Exchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeResponse_Exchange.Unmarshal(m, b)
}
func (m *ExchangeResponse_Exchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeResponse_Exchange.Marshal(b, m, deterministic)
}
func (m *ExchangeResponse_Exchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeResponse_Exchange.Merge(m, src)
}
func (m *ExchangeResponse_Exchange) XXX_Size() int {
	return xxx_messageInfo_ExchangeResponse_Exchange.Size(m)
}
func (m *ExchangeResponse_Exchange) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeResponse_Exchange.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeResponse_Exchange proto.InternalMessageInfo

func (m *ExchangeResponse_Exchange) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ExchangeResponse_Exchange) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ExchangeResponse_Exchange) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

/// Subscription Request
type SubscriptionRequest struct {
	/// Client-assigned id for this request.  Response will include same id
	CorrelationId int64  `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	/// Preferred service (realtime or delayed).
	Service              Service                        `protobuf:"varint,3,opt,name=service,proto3,enum=org.openfeed.Service" json:"service,omitempty"`
	Unsubscribe          bool                           `protobuf:"varint,4,opt,name=unsubscribe,proto3" json:"unsubscribe,omitempty"`
	Requests             []*SubscriptionRequest_Request `protobuf:"bytes,5,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SubscriptionRequest) Reset()         { *m = SubscriptionRequest{} }
func (m *SubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*SubscriptionRequest) ProtoMessage()    {}
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{13}
}

func (m *SubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionRequest.Unmarshal(m, b)
}
func (m *SubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *SubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionRequest.Merge(m, src)
}
func (m *SubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_SubscriptionRequest.Size(m)
}
func (m *SubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionRequest proto.InternalMessageInfo

func (m *SubscriptionRequest) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *SubscriptionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SubscriptionRequest) GetService() Service {
	if m != nil {
		return m.Service
	}
	return Service_UNKNOWN_SERVICE
}

func (m *SubscriptionRequest) GetUnsubscribe() bool {
	if m != nil {
		return m.Unsubscribe
	}
	return false
}

func (m *SubscriptionRequest) GetRequests() []*SubscriptionRequest_Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type SubscriptionRequest_Request struct {
	// Types that are valid to be assigned to Data:
	//	*SubscriptionRequest_Request_Symbol
	//	*SubscriptionRequest_Request_MarketId
	//	*SubscriptionRequest_Request_Exchange
	//	*SubscriptionRequest_Request_ChannelId
	Data             isSubscriptionRequest_Request_Data `protobuf_oneof:"data"`
	SubscriptionType []SubscriptionType                 `protobuf:"varint,10,rep,packed,name=subscriptionType,proto3,enum=org.openfeed.SubscriptionType" json:"subscriptionType,omitempty"`
	/// 0 = send only current snapshot once, else send at interval seconds
	SnapshotIntervalSeconds int32 `protobuf:"zigzag32,11,opt,name=snapshotIntervalSeconds,proto3" json:"snapshotIntervalSeconds,omitempty"`
	/// Spreads and Options must be explicitly requested.
	InstrumentType       []InstrumentDefinition_InstrumentType `protobuf:"varint,12,rep,packed,name=instrumentType,proto3,enum=org.openfeed.InstrumentDefinition_InstrumentType" json:"instrumentType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *SubscriptionRequest_Request) Reset()         { *m = SubscriptionRequest_Request{} }
func (m *SubscriptionRequest_Request) String() string { return proto.CompactTextString(m) }
func (*SubscriptionRequest_Request) ProtoMessage()    {}
func (*SubscriptionRequest_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{13, 0}
}

func (m *SubscriptionRequest_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionRequest_Request.Unmarshal(m, b)
}
func (m *SubscriptionRequest_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionRequest_Request.Marshal(b, m, deterministic)
}
func (m *SubscriptionRequest_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionRequest_Request.Merge(m, src)
}
func (m *SubscriptionRequest_Request) XXX_Size() int {
	return xxx_messageInfo_SubscriptionRequest_Request.Size(m)
}
func (m *SubscriptionRequest_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionRequest_Request.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionRequest_Request proto.InternalMessageInfo

type isSubscriptionRequest_Request_Data interface {
	isSubscriptionRequest_Request_Data()
}

type SubscriptionRequest_Request_Symbol struct {
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3,oneof"`
}

type SubscriptionRequest_Request_MarketId struct {
	MarketId int64 `protobuf:"zigzag64,2,opt,name=marketId,proto3,oneof"`
}

type SubscriptionRequest_Request_Exchange struct {
	Exchange string `protobuf:"bytes,3,opt,name=exchange,proto3,oneof"`
}

type SubscriptionRequest_Request_ChannelId struct {
	ChannelId int32 `protobuf:"zigzag32,4,opt,name=channelId,proto3,oneof"`
}

func (*SubscriptionRequest_Request_Symbol) isSubscriptionRequest_Request_Data() {}

func (*SubscriptionRequest_Request_MarketId) isSubscriptionRequest_Request_Data() {}

func (*SubscriptionRequest_Request_Exchange) isSubscriptionRequest_Request_Data() {}

func (*SubscriptionRequest_Request_ChannelId) isSubscriptionRequest_Request_Data() {}

func (m *SubscriptionRequest_Request) GetData() isSubscriptionRequest_Request_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SubscriptionRequest_Request) GetSymbol() string {
	if x, ok := m.GetData().(*SubscriptionRequest_Request_Symbol); ok {
		return x.Symbol
	}
	return ""
}

func (m *SubscriptionRequest_Request) GetMarketId() int64 {
	if x, ok := m.GetData().(*SubscriptionRequest_Request_MarketId); ok {
		return x.MarketId
	}
	return 0
}

func (m *SubscriptionRequest_Request) GetExchange() string {
	if x, ok := m.GetData().(*SubscriptionRequest_Request_Exchange); ok {
		return x.Exchange
	}
	return ""
}

func (m *SubscriptionRequest_Request) GetChannelId() int32 {
	if x, ok := m.GetData().(*SubscriptionRequest_Request_ChannelId); ok {
		return x.ChannelId
	}
	return 0
}

func (m *SubscriptionRequest_Request) GetSubscriptionType() []SubscriptionType {
	if m != nil {
		return m.SubscriptionType
	}
	return nil
}

func (m *SubscriptionRequest_Request) GetSnapshotIntervalSeconds() int32 {
	if m != nil {
		return m.SnapshotIntervalSeconds
	}
	return 0
}

func (m *SubscriptionRequest_Request) GetInstrumentType() []InstrumentDefinition_InstrumentType {
	if m != nil {
		return m.InstrumentType
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SubscriptionRequest_Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SubscriptionRequest_Request_Symbol)(nil),
		(*SubscriptionRequest_Request_MarketId)(nil),
		(*SubscriptionRequest_Request_Exchange)(nil),
		(*SubscriptionRequest_Request_ChannelId)(nil),
	}
}

type SubscriptionResponse struct {
	CorrelationId        int64            `protobuf:"zigzag64,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Status               *Status          `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Symbol               string           `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MarketId             int64            `protobuf:"zigzag64,4,opt,name=marketId,proto3" json:"marketId,omitempty"`
	Exchange             string           `protobuf:"bytes,5,opt,name=exchange,proto3" json:"exchange,omitempty"`
	ChannelId            int32            `protobuf:"zigzag32,6,opt,name=channelId,proto3" json:"channelId,omitempty"`
	NumberOfDefinitions  int32            `protobuf:"zigzag32,7,opt,name=numberOfDefinitions,proto3" json:"numberOfDefinitions,omitempty"`
	SubscriptionType     SubscriptionType `protobuf:"varint,8,opt,name=subscriptionType,proto3,enum=org.openfeed.SubscriptionType" json:"subscriptionType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SubscriptionResponse) Reset()         { *m = SubscriptionResponse{} }
func (m *SubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*SubscriptionResponse) ProtoMessage()    {}
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be7e080e8e1d40b0, []int{14}
}

func (m *SubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionResponse.Unmarshal(m, b)
}
func (m *SubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *SubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionResponse.Merge(m, src)
}
func (m *SubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_SubscriptionResponse.Size(m)
}
func (m *SubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionResponse proto.InternalMessageInfo

func (m *SubscriptionResponse) GetCorrelationId() int64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *SubscriptionResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SubscriptionResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SubscriptionResponse) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *SubscriptionResponse) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *SubscriptionResponse) GetChannelId() int32 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

func (m *SubscriptionResponse) GetNumberOfDefinitions() int32 {
	if m != nil {
		return m.NumberOfDefinitions
	}
	return 0
}

func (m *SubscriptionResponse) GetSubscriptionType() SubscriptionType {
	if m != nil {
		return m.SubscriptionType
	}
	return SubscriptionType_ALL
}

func init() {
	proto.RegisterEnum("org.openfeed.Result", Result_name, Result_value)
	proto.RegisterEnum("org.openfeed.SubscriptionType", SubscriptionType_name, SubscriptionType_value)
	proto.RegisterType((*OpenfeedGatewayRequest)(nil), "org.openfeed.OpenfeedGatewayRequest")
	proto.RegisterType((*OpenfeedGatewayMessage)(nil), "org.openfeed.OpenfeedGatewayMessage")
	proto.RegisterType((*Status)(nil), "org.openfeed.Status")
	proto.RegisterType((*LoginRequest)(nil), "org.openfeed.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "org.openfeed.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "org.openfeed.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "org.openfeed.LogoutResponse")
	proto.RegisterType((*InstrumentRequest)(nil), "org.openfeed.InstrumentRequest")
	proto.RegisterType((*InstrumentResponse)(nil), "org.openfeed.InstrumentResponse")
	proto.RegisterType((*InstrumentReferenceRequest)(nil), "org.openfeed.InstrumentReferenceRequest")
	proto.RegisterType((*InstrumentReferenceResponse)(nil), "org.openfeed.InstrumentReferenceResponse")
	proto.RegisterType((*ExchangeRequest)(nil), "org.openfeed.ExchangeRequest")
	proto.RegisterType((*ExchangeResponse)(nil), "org.openfeed.ExchangeResponse")
	proto.RegisterType((*ExchangeResponse_Exchange)(nil), "org.openfeed.ExchangeResponse.Exchange")
	proto.RegisterType((*SubscriptionRequest)(nil), "org.openfeed.SubscriptionRequest")
	proto.RegisterType((*SubscriptionRequest_Request)(nil), "org.openfeed.SubscriptionRequest.Request")
	proto.RegisterType((*SubscriptionResponse)(nil), "org.openfeed.SubscriptionResponse")
}

func init() { proto.RegisterFile("openfeed_api.proto", fileDescriptor_be7e080e8e1d40b0) }

var fileDescriptor_be7e080e8e1d40b0 = []byte{
	// 1563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xcb, 0x72, 0xe3, 0x4c,
	0x15, 0xf6, 0x2d, 0xbe, 0x9c, 0x24, 0x8e, 0xd2, 0xc9, 0x9f, 0x18, 0x27, 0xfc, 0x0c, 0x2e, 0x0a,
	0xf2, 0xff, 0x35, 0x15, 0x60, 0x58, 0xc0, 0x12, 0xd9, 0xee, 0x44, 0x62, 0xe4, 0xcb, 0xb4, 0xa4,
	0x30, 0x33, 0x1b, 0x97, 0x62, 0x77, 0x12, 0x33, 0xb6, 0x64, 0x24, 0x39, 0x33, 0xe1, 0x5a, 0x6c,
	0xa8, 0xe2, 0x15, 0x60, 0x03, 0xef, 0xc0, 0x4b, 0xb0, 0x63, 0x35, 0x55, 0xbc, 0x01, 0x8f, 0x41,
	0x75, 0xeb, 0x2e, 0xcb, 0x9e, 0x99, 0x9a, 0x4a, 0x15, 0xff, 0x2a, 0xea, 0xd3, 0xdf, 0xf9, 0xce,
	0xe9, 0x73, 0xeb, 0x76, 0x00, 0x59, 0x0b, 0x6a, 0xde, 0x50, 0x3a, 0x19, 0x19, 0x8b, 0xe9, 0xf9,
	0xc2, 0xb6, 0x5c, 0x0b, 0xed, 0x58, 0xf6, 0xed, 0x79, 0x20, 0x6f, 0x7e, 0x2b, 0x44, 0x4c, 0x4d,
	0xc7, 0xb5, 0x97, 0x73, 0x6a, 0xba, 0x1e, 0xb0, 0x59, 0x0f, 0xb6, 0xbc, 0x75, 0xeb, 0xcf, 0x25,
	0x38, 0x1a, 0xf8, 0xa2, 0x4b, 0xc3, 0xa5, 0x6f, 0x8d, 0x07, 0x42, 0x7f, 0xbd, 0xa4, 0x8e, 0x8b,
	0x7e, 0x0e, 0x3b, 0x33, 0xeb, 0x76, 0x6a, 0xfa, 0xeb, 0x46, 0xfe, 0x49, 0xfe, 0x6c, 0xfb, 0x59,
	0xf3, 0x3c, 0x6e, 0xea, 0x5c, 0x89, 0x21, 0xa4, 0x1c, 0x49, 0x68, 0xa0, 0x0e, 0xec, 0xce, 0xac,
	0x5b, 0x6b, 0xe9, 0x06, 0x14, 0x05, 0x4e, 0x71, 0xb2, 0x42, 0x11, 0x41, 0xa4, 0x1c, 0x49, 0xea,
	0x20, 0x1d, 0x0e, 0x9c, 0xe5, 0xb5, 0x33, 0xb6, 0xa7, 0x0b, 0x77, 0x6a, 0x85, 0xde, 0x14, 0x39,
	0xd5, 0x77, 0x93, 0x54, 0xea, 0x2a, 0x50, 0xca, 0x91, 0x2c, 0x7d, 0x34, 0x80, 0xfd, 0x28, 0x38,
	0x01, 0x69, 0x89, 0x93, 0x7e, 0x27, 0x49, 0x2a, 0xa7, 0x61, 0x52, 0x8e, 0xac, 0xea, 0xa2, 0x5f,
	0x41, 0x33, 0x2e, 0xbc, 0xa1, 0x36, 0x35, 0xc7, 0x34, 0x60, 0xde, 0xe2, 0xcc, 0x67, 0xeb, 0x99,
	0x93, 0x78, 0x29, 0x47, 0x36, 0xb0, 0x21, 0x19, 0xf6, 0xe8, 0xbb, 0xf1, 0x9d, 0x61, 0xde, 0x86,
	0x06, 0xca, 0xdc, 0xc0, 0xb7, 0x93, 0x06, 0x70, 0x12, 0x24, 0xe5, 0x48, 0x5a, 0xaf, 0x5d, 0x86,
	0xd2, 0xc4, 0x70, 0x8d, 0xd6, 0x3f, 0xab, 0x2b, 0x85, 0xd0, 0xa3, 0x8e, 0x63, 0xdc, 0x52, 0x3f,
	0x8d, 0x2c, 0xad, 0xce, 0xc2, 0x32, 0x1d, 0xea, 0x57, 0xc2, 0x49, 0x66, 0x25, 0x78, 0x10, 0x3f,
	0x8d, 0x91, 0x00, 0x5d, 0x40, 0x3d, 0xc8, 0xab, 0xcf, 0xe2, 0x15, 0xc3, 0x69, 0x76, 0x31, 0x84,
	0x34, 0x29, 0x2d, 0x44, 0x00, 0xc5, 0x03, 0xe3, 0x73, 0x79, 0xd5, 0xf0, 0x64, 0x7d, 0x78, 0x43,
	0xbe, 0x0c, 0x6d, 0x34, 0x87, 0x93, 0xcc, 0x60, 0xfb, 0xe4, 0x5e, 0x55, 0x7c, 0xf5, 0x11, 0xb9,
	0x0b, 0xad, 0x6c, 0xe2, 0x43, 0x2f, 0xe1, 0x30, 0x59, 0x91, 0xbe, 0x1d, 0xaf, 0x46, 0x5a, 0x9b,
	0x4a, 0x3a, 0x34, 0x90, 0xc9, 0xc0, 0x5a, 0x76, 0x6e, 0xd8, 0x6f, 0xa8, 0xab, 0xba, 0x86, 0xbb,
	0x74, 0xfc, 0xa2, 0x48, 0xb5, 0x6c, 0x2f, 0x86, 0x60, 0x2d, 0x1b, 0xd7, 0x40, 0x3f, 0x85, 0xda,
	0x1d, 0x35, 0x6c, 0xb7, 0x4d, 0x0d, 0xb7, 0x51, 0xe1, 0xea, 0xc7, 0x49, 0x75, 0x29, 0xd8, 0x96,
	0x72, 0x24, 0xc2, 0xb2, 0x43, 0x45, 0x67, 0xee, 0xd2, 0x9b, 0xa9, 0x39, 0x65, 0xae, 0x35, 0xaa,
	0x59, 0x87, 0x92, 0x33, 0x90, 0xec, 0x50, 0x59, 0x0c, 0xac, 0x72, 0x7c, 0x17, 0x4d, 0x63, 0xe1,
	0xdc, 0x59, 0x6e, 0xa3, 0x96, 0x55, 0x39, 0xbd, 0x04, 0x86, 0x55, 0x4e, 0x52, 0x2b, 0x0a, 0x8e,
	0xbe, 0x98, 0x18, 0x2e, 0x6d, 0xc0, 0xfa, 0xe0, 0x78, 0x88, 0x28, 0x38, 0xde, 0x9a, 0x35, 0xc2,
	0xbd, 0x35, 0x5b, 0xce, 0xa9, 0xe8, 0x0e, 0xed, 0xe9, 0x98, 0x36, 0xb6, 0xb3, 0x1a, 0xe1, 0x2a,
	0x0e, 0x61, 0x8d, 0x90, 0xd0, 0x41, 0x67, 0x50, 0xb2, 0xee, 0x66, 0xe3, 0xc6, 0x0e, 0xd7, 0x45,
	0x49, 0xdd, 0xc1, 0xdd, 0x6c, 0x2c, 0xe5, 0x08, 0x47, 0x20, 0x05, 0x84, 0xa8, 0x5b, 0xfd, 0x1a,
	0xd9, 0xe5, 0x5a, 0x5f, 0xae, 0x6b, 0xf3, 0xb0, 0x3e, 0x56, 0x34, 0x19, 0x5b, 0x14, 0x5e, 0x71,
	0xcc, 0x93, 0x53, 0xcf, 0x62, 0x93, 0x53, 0x28, 0xc6, 0x96, 0xd6, 0x0c, 0xc7, 0xc6, 0x9f, 0xf2,
	0x50, 0xf6, 0x4b, 0xe7, 0x29, 0x94, 0x6d, 0xea, 0x2c, 0x67, 0xde, 0x4d, 0x51, 0x7f, 0x76, 0x98,
	0xa4, 0x25, 0x7c, 0x8f, 0xf8, 0x18, 0xd4, 0x80, 0xca, 0xdc, 0x9b, 0x2f, 0x7c, 0x10, 0xd4, 0x48,
	0xb0, 0x44, 0x3f, 0x84, 0x8a, 0x43, 0xed, 0x7b, 0x16, 0xdf, 0x22, 0x27, 0xfa, 0x22, 0xd5, 0x11,
	0xde, 0x26, 0x09, 0x50, 0xad, 0x19, 0xec, 0xc4, 0xaf, 0x21, 0xf4, 0x3d, 0xd8, 0x1d, 0x5b, 0xb6,
	0x4d, 0x67, 0x06, 0x73, 0x55, 0x9e, 0x70, 0x7f, 0x10, 0x49, 0x0a, 0x51, 0x13, 0xaa, 0x4b, 0x87,
	0xda, 0xa6, 0x31, 0x0f, 0x3c, 0x08, 0xd7, 0x6c, 0x6f, 0x61, 0x38, 0xce, 0x5b, 0xcb, 0x9e, 0x70,
	0x1f, 0x6a, 0x24, 0x5c, 0xb7, 0x1e, 0x60, 0x37, 0x31, 0xea, 0x3e, 0xd2, 0xdc, 0x53, 0x28, 0x3b,
	0x5e, 0x53, 0x7a, 0x73, 0x2f, 0x15, 0x1d, 0x2f, 0x86, 0xc4, 0xc7, 0xa0, 0x43, 0xd8, 0x72, 0xad,
	0x37, 0xd4, 0xf4, 0xad, 0x7b, 0x8b, 0xd6, 0x73, 0x6e, 0x3a, 0x76, 0x37, 0x7e, 0x9c, 0xe9, 0x6c,
	0xb2, 0x09, 0xd4, 0x93, 0xc3, 0xf6, 0x31, 0x0e, 0xd2, 0xfa, 0x77, 0x1e, 0xf6, 0x57, 0x2e, 0xd0,
	0x4f, 0xf5, 0xbb, 0x10, 0xf3, 0x1b, 0x35, 0xa0, 0xec, 0x3c, 0xcc, 0xaf, 0xad, 0x19, 0x6f, 0xe0,
	0x9a, 0x94, 0x23, 0xfe, 0x1a, 0x9d, 0x42, 0xd5, 0x6b, 0x57, 0x79, 0xc2, 0x3b, 0x13, 0x49, 0x39,
	0x12, 0x4a, 0xd8, 0x6e, 0xd0, 0x13, 0xbc, 0xf7, 0x98, 0x66, 0x28, 0x41, 0x5f, 0x42, 0x8d, 0x7d,
	0x99, 0x74, 0x26, 0x4f, 0x78, 0x93, 0xed, 0xb3, 0xf1, 0x16, 0x8a, 0xda, 0x35, 0xa8, 0xd8, 0x9e,
	0xf3, 0xad, 0xbf, 0xe6, 0x01, 0xad, 0x5e, 0x2d, 0x8f, 0x52, 0x06, 0x3f, 0x82, 0x03, 0x73, 0x39,
	0xbf, 0xa6, 0xf6, 0xe0, 0x26, 0x1a, 0x88, 0x0e, 0xcf, 0xe3, 0x3e, 0xc9, 0xda, 0x6a, 0xfd, 0x27,
	0x0f, 0xcd, 0xf5, 0xcf, 0x8a, 0x6f, 0x76, 0xe0, 0xff, 0x56, 0x84, 0x93, 0x0d, 0xd7, 0xee, 0xff,
	0x47, 0x06, 0xd0, 0x69, 0xfc, 0x40, 0x25, 0x8e, 0x8b, 0x04, 0x6c, 0xb2, 0x84, 0xa1, 0xda, 0xe2,
	0xee, 0x45, 0x81, 0x3a, 0x0a, 0x03, 0x5c, 0xe6, 0x71, 0x0f, 0xc2, 0xdb, 0x8c, 0x05, 0xb0, 0xe2,
	0x4d, 0xa3, 0x30, 0x7c, 0xa7, 0x50, 0x9b, 0x4c, 0x6e, 0x54, 0x4f, 0xad, 0xca, 0x37, 0x23, 0x01,
	0x7a, 0x02, 0xdb, 0x93, 0xc9, 0x4d, 0x70, 0x3d, 0xf0, 0x7b, 0xb3, 0x46, 0xe2, 0x22, 0x1f, 0xd1,
	0x36, 0x1c, 0xda, 0xb1, 0x26, 0xde, 0x9d, 0xe8, 0x21, 0x02, 0x11, 0xfa, 0x3e, 0xd4, 0x03, 0x6b,
	0xbe, 0x99, 0x6d, 0x0e, 0x4a, 0x49, 0x5b, 0x3d, 0xd8, 0x4b, 0x3d, 0x37, 0x3f, 0xa7, 0xda, 0x5a,
	0x7f, 0x29, 0x80, 0x90, 0xbe, 0xd7, 0x1e, 0x25, 0xc3, 0x18, 0x6a, 0xc1, 0x49, 0x58, 0x5e, 0x8b,
	0x67, 0xdb, 0xcf, 0x7e, 0xb0, 0xf9, 0x7a, 0x8d, 0x04, 0x91, 0x66, 0xf3, 0x35, 0x54, 0xc3, 0xa0,
	0x22, 0x28, 0x8d, 0x59, 0x34, 0xf3, 0xfc, 0x40, 0xfc, 0x9b, 0x07, 0x9a, 0x86, 0x2f, 0x36, 0xff,
	0xac, 0x71, 0x11, 0xbb, 0x11, 0x8d, 0xd9, 0xd4, 0x70, 0x7c, 0x37, 0x6a, 0x24, 0x58, 0xb6, 0xde,
	0x97, 0xe0, 0x20, 0xe3, 0xa7, 0xcd, 0x67, 0x75, 0xf3, 0xa7, 0xde, 0xb2, 0xec, 0x00, 0x4b, 0xd3,
	0x7f, 0x75, 0x5e, 0x7b, 0x8f, 0xe2, 0x2a, 0x89, 0x8b, 0x10, 0x86, 0xaa, 0xdf, 0xaa, 0x4e, 0x63,
	0x8b, 0x07, 0xf2, 0xab, 0x0f, 0xfe, 0x3c, 0x3b, 0xf7, 0xff, 0x92, 0x50, 0xb5, 0xf9, 0xdf, 0x02,
	0x54, 0x82, 0x13, 0x46, 0x33, 0x27, 0xbf, 0x61, 0xe6, 0x14, 0x36, 0xce, 0x9c, 0xe2, 0xe6, 0x99,
	0x53, 0x5a, 0x99, 0x39, 0xe8, 0x17, 0x20, 0xc4, 0x9f, 0xd7, 0xda, 0xc3, 0x82, 0x75, 0x46, 0xf1,
	0xac, 0x9e, 0x7e, 0x2a, 0xa9, 0x29, 0x14, 0x59, 0xd1, 0x43, 0x3f, 0x83, 0x63, 0xc7, 0x7f, 0x81,
	0xca, 0xa6, 0x4b, 0xed, 0x7b, 0x63, 0xa6, 0xd2, 0xb1, 0x65, 0x4e, 0x1c, 0xde, 0x47, 0xfb, 0x64,
	0xdd, 0x36, 0x7a, 0x05, 0xf5, 0xe8, 0xd9, 0xc5, 0x7d, 0xd8, 0xe1, 0x3e, 0xfc, 0xf8, 0xc3, 0x6f,
	0xe9, 0x98, 0x90, 0xbb, 0x95, 0x22, 0x0a, 0x5f, 0x6f, 0xef, 0x0b, 0x70, 0x98, 0xf5, 0x03, 0xe3,
	0x51, 0x1a, 0x2d, 0x1a, 0x6f, 0xc5, 0xf4, 0x78, 0x0b, 0x33, 0x59, 0x4a, 0x8d, 0xc4, 0xf8, 0xe8,
	0xdb, 0x5a, 0x1d, 0x7d, 0x51, 0x16, 0xcb, 0xe9, 0x41, 0xbb, 0x66, 0x70, 0x57, 0xd6, 0x0f, 0xee,
	0xac, 0xac, 0x57, 0x79, 0x6b, 0x7c, 0x72, 0xd6, 0xbf, 0xfe, 0x57, 0x01, 0xca, 0xde, 0x83, 0x17,
	0x21, 0xa8, 0xeb, 0xfd, 0xe7, 0xfd, 0xc1, 0x2f, 0xfb, 0x23, 0x82, 0x55, 0x5d, 0xd1, 0x84, 0x1c,
	0xda, 0x86, 0x8a, 0xaa, 0x77, 0x3a, 0x58, 0x55, 0x85, 0x3c, 0x03, 0xc8, 0xfd, 0x2b, 0x51, 0x91,
	0xbb, 0x23, 0xf5, 0x55, 0xaf, 0x3d, 0x50, 0x04, 0x17, 0x7d, 0x01, 0xfb, 0x81, 0xac, 0x27, 0x92,
	0xe7, 0x58, 0x1b, 0xc9, 0x5d, 0x61, 0x89, 0x0e, 0x41, 0x08, 0xc4, 0xf8, 0x65, 0x47, 0x12, 0xfb,
	0x97, 0x58, 0xb8, 0x47, 0x47, 0x80, 0x02, 0x29, 0x93, 0xf5, 0xb1, 0xc2, 0xd0, 0x6f, 0x19, 0x49,
	0x4f, 0x54, 0x2e, 0x06, 0xa4, 0x87, 0xbb, 0xa3, 0x1e, 0x56, 0x55, 0xf1, 0x12, 0x0b, 0xef, 0x18,
	0x5c, 0xef, 0xe3, 0x97, 0x43, 0xdc, 0xd1, 0x62, 0xf2, 0x07, 0xe6, 0x47, 0x7f, 0xa0, 0x8d, 0x54,
	0xbd, 0xad, 0x76, 0x88, 0xdc, 0xc6, 0x5d, 0xe1, 0x37, 0xa8, 0x09, 0x47, 0x5d, 0x7d, 0xa8, 0xc8,
	0x1d, 0x51, 0xc3, 0xc1, 0xce, 0x50, 0x93, 0x07, 0x7d, 0xe1, 0xb7, 0xe8, 0x18, 0x0e, 0x42, 0xb3,
	0x04, 0x77, 0x71, 0x5f, 0x93, 0x45, 0x45, 0x15, 0x7e, 0x87, 0x4e, 0xe0, 0x58, 0xee, 0xab, 0xfa,
	0xc5, 0x85, 0xdc, 0x91, 0x71, 0x5f, 0x1b, 0x0d, 0x89, 0x7c, 0x25, 0x2b, 0xf8, 0x12, 0xab, 0xc2,
	0xef, 0xd9, 0xa6, 0xa8, 0x6b, 0x12, 0x43, 0x77, 0x44, 0xc6, 0x34, 0x22, 0xf8, 0x85, 0x2e, 0x13,
	0xdc, 0x15, 0xfe, 0x80, 0x0e, 0x60, 0xef, 0x12, 0xf7, 0x31, 0x91, 0x3b, 0xa3, 0x0b, 0x51, 0x56,
	0x74, 0x82, 0x85, 0x3f, 0x7e, 0xfd, 0x8f, 0x3c, 0x08, 0xe9, 0x90, 0xa3, 0x0a, 0x14, 0x45, 0x45,
	0x11, 0x72, 0xa8, 0x06, 0x5b, 0x2f, 0xf4, 0x81, 0x86, 0x85, 0x3c, 0x3b, 0x2f, 0xff, 0x1c, 0x0d,
	0x45, 0xa2, 0xc9, 0x1d, 0x79, 0x28, 0xf6, 0x35, 0xa1, 0x80, 0xf6, 0x60, 0xbb, 0x8b, 0x87, 0x9a,
	0xc4, 0xfc, 0xe8, 0x60, 0xa1, 0x18, 0x09, 0x06, 0xa4, 0x8b, 0x89, 0x50, 0x42, 0x00, 0x65, 0x8d,
	0x88, 0x5d, 0xac, 0x0a, 0x5b, 0x2c, 0xc4, 0x1d, 0xbd, 0xa7, 0x88, 0x9a, 0x7c, 0x85, 0x47, 0x57,
	0x03, 0x45, 0xef, 0x61, 0xa1, 0x8c, 0xaa, 0x50, 0x1a, 0x48, 0x4a, 0x47, 0xa8, 0xb0, 0x7d, 0xf6,
	0x35, 0xea, 0x73, 0xcf, 0x2f, 0x75, 0x45, 0x24, 0x42, 0xb5, 0xbd, 0x2f, 0xe5, 0x87, 0xf9, 0xd7,
	0xd5, 0xa0, 0x44, 0xfe, 0x9e, 0xcf, 0x5f, 0x97, 0xf9, 0x3f, 0xd8, 0x7e, 0xf2, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x43, 0x5c, 0xe5, 0xee, 0xaf, 0x13, 0x00, 0x00,
}
